server.port=3000

# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/loadlens
spring.datasource.username=postgres
spring.datasource.password=1976
# Hibernate/JPA settings
# ddl -> change in java show change in db
spring.jpa.hibernate.ddl-auto=update
# BTS sql command will be shown
spring.jpa.show-sql=true
# format the sql queries
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never